name: Deploy HackTricks Book to GitHub Pages

on:
  push:
    branches:
      - main # 当 main 分支有推送时触发，您可以更改为您的主要分支
  workflow_dispatch: # 允许手动触发

# 设置 GITHUB_TOKEN 的权限，以便部署到 GitHub Pages
permissions:
  contents: read # 需要读取仓库内容
  pages: write   # 需要写入 GitHub Pages
  id-token: write # 需要 OIDC token 进行身份验证

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: # 指定部署环境 (可选，但推荐)
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # 输出部署后的 URL

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # 检出您自己的仓库 (如果 mdBook 源文件在其中)

      - name: Clone HackTricks and Select Language
        env:
          # 您想要构建的语言版本，与您之前的脚本中的 LANG 变量对应
          # "master" 代表英语, "zh" 代表中文, 等等.
          BOOK_LANG: "zh" # <<-------------------- 在这里设置您想要的语言
        run: |
          git clone https://github.com/HackTricks-wiki/hacktricks.git
          cd hacktricks
          echo "Checking out language: $BOOK_LANG"
          git checkout $BOOK_LANG
          git pull origin $BOOK_LANG # 确保获取最新的语言内容
          echo "Current branch and commit after checkout:"
          git branch
          git log -1
          cd .. # 返回工作区根目录

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1 # 一个流行的安装 mdBook 的 Action
        with:
          mdbook-version: 'latest' # 或者指定一个版本，例如 '0.4.36'

      - name: Build mdBook
        run: |
          echo "Building mdBook from directory: $(pwd)/hacktricks"
          mdbook build ./hacktricks # 从 hacktricks 子目录构建
                                     # mdBook 会在 hacktricks/book/ 目录中生成输出

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 从 mdBook 构建输出的目录上传
          path: './hacktricks/book' # <<---- 确保这个路径正确

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
