name: Run HackTricks

on: [push] # 您可以根据需要更改触发器，例如 [workflow_dispatch] 手动触发

jobs:
  run_hacktricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 使用最新的 checkout action

      - name: Run HackTricks Script
        run: |
          # Download latest version of hacktricks
          git clone https://github.com/HackTricks-wiki/hacktricks

          # Select the language you want to use
          export LANG="zh" # Leave master for english
          # "af" for Afrikaans
          # "de" for German
          # "el" for Greek
          # "es" for Spanish
          # "fr" for French
          # "hi" for Hindi
          # "it" for Italian
          # "ja" for Japanese
          # "ko" for Korean
          # "pl" for Polish
          # "pt" for Portuguese
          # "sr" for Serbian
          # "sw" for Swahili
          # "tr" for Turkish
          # "uk" for Ukrainian
          # "zh" for Chinese

          # Run the docker container indicating the path to the hacktricks folder
          docker run -d --rm --platform linux/amd64 -p 3337:3000 --name hacktricks -v $(pwd)/hacktricks:/app ghcr.io/hacktricks-wiki/hacktricks-cloud/translator-image bash -c "cd /app && git config --global --add safe.directory /app && git checkout $LANG && git pull && MDBOOK_PREPROCESSOR__HACKTRICKS__ENV=dev mdbook serve --hostname 0.0.0.0"

          # 添加一个小的延迟以确保容器有足够的时间启动（可选）
          # echo "Waiting for HackTricks container to start..."
          # sleep 30

          # 您可以在此处添加其他步骤，例如检查容器是否正在运行或访问服务
          # 例如： curl http://localhost:3337
